export interface Hobby {
  id: number
  title: string
  location: string
  price: string
  rating: number
  image: string
  category: string
}

export const hobbyData: Hobby[] = [
  {
    id: 1,
    title: '수채화 드로잉',
    location: '강남구',
    price: '50,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=1',
    category: '미술',
  },
  {
    id: 2,
    title: '홈베이킹 클래스',
    location: '서초구',
    price: '35,000원',
    rating: 4.9,
    image: 'https://picsum.photos/300/200?random=2',
    category: '요리',
  },
  {
    id: 3,
    title: '요가 & 명상',
    location: '마포구',
    price: '40,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=3',
    category: '운동',
  },
  {
    id: 4,
    title: '플라워 아레인지먼트',
    location: '송파구',
    price: '45,000원',
    rating: 4.6,
    image: 'https://picsum.photos/300/200?random=4',
    category: '공예',
  },
  {
    id: 5,
    title: '기타 레슨',
    location: '서초구',
    price: '45,000원',
    rating: 4.6,
    image: 'https://picsum.photos/300/200?random=13',
    category: '음악',
  },
  {
    id: 6,
    title: '독서 모임',
    location: '마포구',
    price: '25,000원',
    rating: 4.4,
    image: 'https://picsum.photos/300/200?random=17',
    category: '독서',
  },
  {
    id: 7,
    title: '필라테스 기초',
    location: '송파구',
    price: '50,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=11',
    category: '운동',
  },
  {
    id: 8,
    title: '도자기 만들기',
    location: '용산구',
    price: '55,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=16',
    category: '공예',
  },
  {
    id: 9,
    title: '바리스타 자격증',
    location: '마포구',
    price: '120,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=21',
    category: '요리',
  },
  {
    id: 10,
    title: '캘리그래피',
    location: '마포구',
    price: '35,000원',
    rating: 4.5,
    image: 'https://picsum.photos/300/200?random=27',
    category: '미술',
  },
  {
    id: 11,
    title: '테니스 레슨',
    location: '강남구',
    price: '65,000원',
    rating: 4.6,
    image: 'https://picsum.photos/300/200?random=20',
    category: '운동',
  },
  {
    id: 12,
    title: '드럼 레슨',
    location: '용산구',
    price: '50,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=24',
    category: '음악',
  },
  {
    id: 13,
    title: '아크릴 페인팅',
    location: '서초구',
    price: '45,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=28',
    category: '미술',
  },
  {
    id: 14,
    title: '이탈리안 요리',
    location: '강남구',
    price: '55,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=29',
    category: '요리',
  },
  {
    id: 15,
    title: '피아노 레슨',
    location: '강남구',
    price: '50,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=30',
    category: '음악',
  },
  {
    id: 16,
    title: '가죽공예',
    location: '마포구',
    price: '60,000원',
    rating: 4.8,
    image: 'https://picsum.photos/300/200?random=31',
    category: '공예',
  },
  {
    id: 17,
    title: '책 리뷰 클럽',
    location: '서초구',
    price: '30,000원',
    rating: 4.5,
    image: 'https://picsum.photos/300/200?random=32',
    category: '독서',
  },
  {
    id: 18,
    title: '디지털 드로잉',
    location: '송파구',
    price: '60,000원',
    rating: 4.9,
    image: 'https://picsum.photos/300/200?random=33',
    category: '미술',
  },
  {
    id: 19,
    title: '디저트 만들기',
    location: '마포구',
    price: '40,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=34',
    category: '요리',
  },
  {
    id: 20,
    title: '목공예',
    location: '강남구',
    price: '70,000원',
    rating: 4.7,
    image: 'https://picsum.photos/300/200?random=35',
    category: '공예',
  },
  {
    id: 21,
    title: '보컬 트레이닝',
    location: '마포구',
    price: '55,000원',
    rating: 4.6,
    image: 'https://picsum.photos/300/200?random=36',
    category: '음악',
  },
  {
    id: 22,
    title: '에세이 쓰기',
    location: '강남구',
    price: '40,000원',
    rating: 4.6,
    image: 'https://picsum.photos/300/200?random=37',
    category: '독서',
  },
  {
    id: 23,
    title: '수영',
    location: '서초구',
    price: '45,000원',
    rating: 4.5,
    image: 'https://picsum.photos/300/200?random=38',
    category: '운동',
  },
  {
    id: 24,
    title: '문학 작품 감상',
    location: '송파구',
    price: '35,000원',
    rating: 4.5,
    image: 'https://picsum.photos/300/200?random=39',
    category: '독서',
  }
]
